version: 2
jobs:
  fetch_docker_image:
    docker:
      - image: rust:1.33.0
    steps:
      - checkout
  build:
    docker:
      - image: rust:1.33.0
    steps:
      - checkout
      - run:
          name: build
          command: cargo build --release
      - persist_to_workspace:
          root: target/release
          paths:
            - xebia-cli
  smoke_test:
    docker:
      - image: rust:1.33.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Execute binary with --help"
          command: ./xebia-cli --help
      - run:
          name: "Execute binary with --help and check that output looks ok-ish"
          command: ./xebia-cli --help | head -n1 | grep xebia-cli

workflows:
  version: 2
  full:
    jobs:
      - fetch_docker_image
      - build:
          requires:
            - fetch_docker_image
      - smoke_test:
          requires:
            - build
